lib:
	(cd ..; $(MAKE) lib)
clean:
	(cd ..; $(MAKE) clean)
verycleanlib:
	(cd ..; $(MAKE) verycleanlib)
testmm: 
	(cd ..; $(MAKE) testmm)
df_sample: 
	(cd ..; $(MAKE) clean clean df_sample)
df_samplem: 
	(cd ..; $(MAKE) clean clean df_samplem)
zf_sample:
	(cd ..; $(MAKE) clean zf_sample)
.PHONY: df_sample zf_sample testmm df_samplem
