      INTEGER FUNCTION PSI_LIST_SEARCH(LIST,LENGHT_LIST,ELEM)
C      !RETURNS POSITION OF ELEM IN A ARRAY LIST
C      !OF LENGHT LENGHT_LIST, IF THIS ELEMENT NOT EXISTS
C      !RETURNS -1
      INTEGER LIST(*)
      INTEGER LENGHT_LIST
      INTEGER ELEM
      
      INTEGER I

      I=1
      DO WHILE ((I.LE.LENGHT_LIST).AND.(LIST(I).NE.ELEM))
         I=I+1
      ENDDO
      IF (I.LE.LENGHT_LIST)  THEN 
         IF (LIST(I).EQ.ELEM) THEN
            PSI_LIST_SEARCH=I
         ELSE
            PSI_LIST_SEARCH=-1
         ENDIF
      ELSE
         PSI_LIST_SEARCH=-1
      ENDIF
      END
         
