include ../Make.inc

lib:
	(cd modules; make lib)
	(cd comm; make lib)
	(cd internals; make lib)
	(cd tools; make lib)
	(cd serial; make lib)
	(cd psblas; make lib)
	(cd prec; make lib)
	(cd methd; make lib)
clean: 
	(cd modules; make clean)
	(cd comm; make clean)
	(cd internals; make clean)
	(cd tools; make clean)
	(cd serial; make clean)
	(cd psblas; make clean)
	(cd prec; make clean)
	(cd methd; make clean)

veryclean: 
	(cd modules; make veryclean)
	(cd comm; make veryclean)
	(cd internals; make veryclean)
	(cd tools; make veryclean)
	(cd serial; make veryclean)
	(cd psblas; make veryclean)
	(cd prec; make veryclean)
	(cd methd; make veryclean)
